version: '3.8'

services:
  redis-master:
    image: redis:7
    container_name: redis-master
    ports:
      - "6379:6379"
    volumes:
      - redis-master-data:/data
    networks:
      - meteor-social

  redis-slave:
    image: redis:7
    container_name: redis-slave
    command: ["redis-server", "--replicaof", "redis-master", "6379"]
    depends_on:
      - redis-master
    ports:
      - "6479:6379"
    volumes:
      - redis-slave-data:/data
    networks:
      - meteor-social
  #Redis-Insight
  redis-stack:
    image: redis/redis-stack:latest
    container_name: redis-stack
    ports:
      - "8001:8001"
    networks:
      - meteor-social

volumes:
  redis-master-data:
  redis-slave-data:

networks:
  meteor-social:
    external: true