services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    container_name: elasticsearch
    environment:
      - node.name=es-node-1
      - cluster.name=es-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - ELASTIC_PASSWORD=35701537Scss
      - xpack.security.enabled=false
      # - xpack.security.enrollment.enabled=true
      # - xpack.security.http.ssl.enabled=true
      # - xpack.security.http.ssl.keystore.path=/usr/share/elasticsearch/config/certs/http.p12
      # Nếu lúc tạo http.p12 có đặt password:
      # - xpack.security.http.ssl.keystore.password=<PASSWORD_KESTORE>
      # - xpack.security.transport.ssl.enabled=true
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ulimits:
      memlock: { soft: -1, hard: -1 }
    ports:
      - '9200:9200'
    networks: [meteor-social]
    volumes:
      - es_data:/usr/share/elasticsearch/data
      # Nếu bạn muốn giữ certs qua restart bằng volume riêng (khuyến nghị):
      # - es_certs:/usr/share/elasticsearch/config/certs

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.0
    container_name: kibana
    depends_on: [elasticsearch]
    # Enrollment sẽ tự cấu hình, VÌ THẾ GỠ các biến dưới:
    # environment:
    #   - ELASTICSEARCH_HOSTS=...
    #   - ELASTICSEARCH_SERVICE_ACCOUNT_TOKEN=...
    ports:
      - '5601:5601'
    networks: [meteor-social]

volumes:
  es_data:
  # es_certs:   # nếu bạn dùng volume riêng cho certs

networks:
  meteor-social:
    external: true
